// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjkprdnocgjyxsbkvaad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqa3ByZG5vY2dqeXhzYmt2YWFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDkyNDQsImV4cCI6MjA2MDI4NTI0NH0.rkfgma21wctkI1dXCeRfYVXQ3EmI9w09JO5Ahm8Mz5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);